#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.osx` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# --------------–-------–--------–--------–-------–--–-----
# System interface and behaviour
# --------------–-------–--------–--------–-------–--–-----
# Check for software updates daily, not just once per week
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

# Save to disk (not to iCloud) by default
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool "false"

# --------------–-------–--------–--------–-------–--–-----
# Trackpad, mouse and keyboard
# --------------–-------–--------–--------–-------–--–-----
# Enable tap to click
defaults write com.apple.AppleMultitouchTrackpad Clicking -bool "true"

# Enable two-tap to right click
defaults write com.apple.AppleMultitouchTrackpad TrackpadRightClick -bool "true"

# Enable dragging without drag lock
defaults write com.apple.AppleMultitouchTrackpad "Dragging" -bool "true"

# --------------–-------–--------–--------–-------–--–-----
# Dock, Dashboard and Menu Bar
# --------------–-------–--------–--------–-------–--–-----
defaults write com.apple.dock "show-recents" -bool "false"

defaults write com.apple.dock "mineffect" -string "scale"

# --------------–-------–--------–--------–-------–--–-----
# Finder
# --------------–-------–--------–--------–-------–--–-----
# Enable spring loading for directories
defaults write NSGlobalDomain com.apple.springing.enabled -bool "true"

# Remove the spring loading delay for directories
defaults write NSGlobalDomain com.apple.springing.delay -float 0

# --------------–-------–--------–--------–-------–--–-----
# Finder
# --------------–-------–--------–--------–-------–--–-----
# Disable window animations and Get Info animations
defaults write com.apple.finder DisableAllAnimations -bool true

# Focus follow mouse
defaults write com.apple.Terminal "FocusFollowsMouse" -bool "true"

# Show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool "true"

# Search in current folder
defaults write com.apple.finder "FXDefaultSearchScope" -string "SCcf"

# Use list view in all Finder windows
defaults write com.apple.finder "FXPreferredViewStyle" -string "Nlsv"

# Show path bar
defaults write com.apple.finder "ShowPathbar" -bool "true"

# Enable spring loading for directories
defaults write NSGlobalDomain com.apple.springing.enabled -bool "true"

# Remove the spring loading delay for directories
defaults write NSGlobalDomain com.apple.springing.delay -float 0

# --------------–-------–--------–--------–-------–--–-----
# Kill affected applications
# --------------–-------–--------–--------–-------–--–-----
for app in "Activity Monitor" "Dock" "Finder" "Transmission" \
           "SystemUIServer" "ControlStrip"; do
  killall "${app}" > /dev/null 2>&1
done
echo "✓ macos OK. Some of these changes require a logout/restart to take effect."
