call plug#begin()
	Plug 'neoclide/coc.nvim', { 'branch': 'release' }
  Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
	Plug 'junegunn/fzf.vim'
	Plug 'Yggdroot/indentLine'
  Plug 'rose-pine/vim'
	Plug 'itchyny/lightline.vim'
call plug#end()

set background=light
colorscheme rosepine_dawn
let g:disable_bg = 1
let g:lightline = {
      \ 'colorscheme': 'rosepine_dawn',
      \ }

let g:fzf_preview_window = []
let $FZF_DEFAULT_OPTS="--preview-window 'right:60%' --layout reverse --margin=0,0 --preview 'bat --color=always --style=header,grid --line-range :300 {}'"

let g:fzf_layout =
\ { 'window':
  \ { 'width': 0.98, 'height': 0.7, 'yoffset': 0.94, 'border': 'rounded' }
\ }

let g:fzf_colors =
\ { 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Comment'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Statement'],
  \ 'info':    ['fg', 'PreProc'],
  \ 'border':  ['fg', 'Ignore'],
  \ 'prompt':  ['fg', 'Conditional'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment'] }

let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_winsize = 25

let mapleader = ';'

syntax on
set encoding=utf-8
set nocompatible
set noshowmode

set number
set relativenumber
set hidden
set scrolloff=5
set showmatch
set laststatus=2
set mouse=a
set clipboard=unnamed

set tabstop=2
set softtabstop=2
set shiftwidth=2
set autoindent
set smartindent
set smarttab
set expandtab

set ignorecase
set smartcase
set incsearch
set hlsearch

set noswapfile
set nobackup
set nowritebackup

set undodir=~/.vim/backups
set undofile

noremap <leader>q :q<CR>
noremap <leader>w :w<CR>
noremap <leader>j :vert terminal<CR>
noremap <leader>o :Buffers<CR>
noremap <leader>p :FZF<CR>
noremap <leader>b :Vexplore<CR>
noremap <leader>t :tabnew<CR>

nnoremap <silent> K :call ShowDocumentation()<CR>

function! ShowDocumentation()
  if CocAction('hasProvider', 'hover')
    call CocActionAsync('doHover')
  else
    call feedkeys('K', 'in')
  endif
endfunction

