" user interface
syntax on
set nonumber
set ruler
set showmode

" misc
let mapleader=","
set nocompatible
set scrolloff=5
set hidden
set noshowmatch
set history=100
set ttyfast
set backspace=indent,eol,start

" tab behavior & indentation style
set expandtab
set tabstop=2
set softtabstop=2
set autoindent
set smartindent
set smarttab

" searching behavior
set ignorecase
set smartcase
set incsearch
set hlsearch

" backup
set noswapfile
set nobackup
set nowritebackup

" undo history
set undodir=~/.vim/backups
set undofile

" key mapping
noremap <leader>d <C-d>
noremap <leader>b <C-b>
noremap <silent> <leader><CR> :nohl<CR>
